def cargar_mapa():
  global map
  mapa.append("################")
  mapa.append("#.....#........#")
  mapa.append("#.....#........#")
  mapa.append("#.....#........#")
  mapa.append("#.....##..##...#")
  mapa.append("#..........#...#")
  mapa.append("#...#......#...#")
  mapa.append("#..............#")
  mapa.append("#..............#")
  mapa.append("####...##..##.##")
  mapa.append("#......#.......#")
  mapa.append("#......#.......#")
  mapa.append("################")